version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: telemedicina_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./nodejs-Telemedicina
    container_name: api_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:1234@database:3306/telemedicina_db
      - JWT_SECRET=clave_secreta_pucv_2026
      - EMAIL_USER=yellowritapink@gmail.com
      - EMAIL_PASS=beowgocmujhqaqob
    depends_on:
      - database

  frontend:
    build:
      context: ./Ionic-Telemedicina
      args:
        - VITE_API_URL=https://curly-space-carnival-wrxrvqwgx4qv3vg5-3000.app.github.dev/api
    container_name: ionic_frontend
    restart: always
    ports:
      - "8100:5173"
    depends_on:
      - backend

volumes:
  mysql_data: